### ISSUE TITLE
Unterschiedliche Back Buttons

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [BogyMitutoyoCTL/Checklisten-App-2022.1#31]
Bei den Settings haben wir einen schwarzen Back Button in der Mitte

![grafik](https://user-images.githubusercontent.com/25632350/162389895-6bb9c06b-070a-4a68-a904-2cb13ae5cd12.png)

Beim Abhaken einer Checkliste haben wir einen blauen Back-Button links

![grafik](https://user-images.githubusercontent.com/25632350/162389988-a13b9c5c-e08b-444e-9fd0-e820eff01fba.png)

**Comment by TimmyBurn** [comment]
Ist das relevant?
