### ISSUE TITLE
Beim ersten Start kommt man von languages zu choose theme, wenn man dann ein theme auswählt kommt man wieder zu languages, wenn man da weiter geht kommt ein blacksreen

### ISSUE THREAD

**Issue by TimmyBurn** [BogyMitutoyoCTL/Checklisten-App-2022.1#43]

**Comment by thomasw-mitutoyo-ctl** [comment]
Den Bug habe ich zusammen mit der Überarbeitung der Speicherung behoben.
Dadurch dass `firstStart` jetzt nur noch an einer Stelle gespeichert wird und nicht mehr in jedem Widget einzeln, hat sich dieser Bug aufgelöst.
